config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]

  root to: 'movies#index'

  namespace :admin do
    resources :users
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  scope :search, -> (query) { where("title LIKE :search OR director LIKE :search", search: "%#{query}%") }

  scope :runtime, -> (runtime) { where(runtime_search(runtime)) }

  has_many :reviews

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  mount_uploader :image, PosterUploader

  def review_average
    if reviews.size == 0
      "No reviews for this movie."
    else
      reviews.sum(:rating_out_of_ten)/reviews.size.to_f
    end
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

  def self.runtime_search(choice)
    case choice
    when "0"
       ""
    when "1"
       "runtime_in_minutes < 90"
    when "2"
       "runtime_in_minutes BETWEEN 90 AND 120"
    when "3"
       "runtime_in_minutes > 120"
    end
  end

  # Used to check if params being passed from search is blank or not.
  # If not blank, it would add wildcards.
  # Decided to move .blank? to controller
  # def self.property_info(property)
  #   if property.blank?
  #     ''
  #   else
  #     "%#{property}%"
  #   end
  # end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

  # validates :rating_out_of_ten,
  #   numericality: { greater_than_or_equal_to: 1 }

  # validates :rating_out_of_ten,
  #   numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :reviews

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

    def full_name
      "#{firstname} #{lastname}"
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :admin_restrict_access

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path(@user), notice: "User created: #{@user.firstname} #{@user.lastname}"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      UserMailer.delete_user(@user).deliver
    end
    redirect_to admin_users_path, notice: "#{@user.email} deleted"
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def admin_restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    elsif !current_user.admin?
      flash[:alert] = "You do not have access to this page"
      redirect_to '/'
    end

  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    @movies = @movies.search(params[:query]) unless params[:query].blank?
    @movies = @movies.runtime(params[:runtime]) if params[:runtime]
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes,
      :poster_image_url, :description, :image, :remote_image_url,
      :remove_image
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie, :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b, %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin, "Admin user?" %> <br />
    <%= f.check_box :admin %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<p><%= link_to "Back to all users", admin_users_path %></p>

<h2>Edit user</h2>

<%= render '/admin/users/form' %>

app/views/admin/users/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Back to Admin Dashboard (placeholder)" %>
<hr>

<p><%= link_to "Create new user", new_admin_user_path %></p>

<h4><%= paginate @users %></h4>

<% @users.each do |user| %>
  <p><%= user.id %>. <%= link_to "#{user.firstname} #{user.lastname}", admin_user_path(user) %> (<%= user.email %>)</p>
<% end %>

<hr>

app/views/admin/users/new.html.erb
<p><%= link_to "Back to all users", admin_users_path %></p>

<%= render '/admin/users/form' %>

app/views/admin/users/show.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Back to all users", admin_users_path %><br>
<hr>

<p>User ID: <%= @user.id %> </p>

<p>First name: <%= @user.firstname %></p>
<p>Last name: <%= @user.lastname %></p>
<p>Email: <%= @user.email %></p>
<p>Admin: <%= @user.admin %></p>
<p>Created at: <%= @user.created_at %></p>
<p>Created at: <%= @user.updated_at %></p>

<br>

<p>( <%= link_to "edit", edit_admin_user_path(@user) %> | <%= link_to "delete", admin_user_path(@user), method: :delete, prompt: "You sure?" %> )</p>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", sessions_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_sessions_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

  <div class="container">

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value) %>
    <% end %>

    <%= yield %>


    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/movies/_movie.html.erb
<%= link_to image_tag(movie.image.thumb.url), movie_path(movie) %>
<h2><%= link_to movie.title, movie_path(movie) %></h2>
<h3><%= formatted_date(movie.release_date) %></h3>
<h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
<p>Average rating from users: <%= movie.review_average %>/10</p>
<p><%= movie.description %></p>

<hr>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Home", movies_path %>   |   <%= link_to "Submit a movie!", new_movie_path %>   |   <%= link_to "Admin users page", admin_users_path %>

<hr>

<%= form_tag(movies_path, method: "get") do %>
  <%= label_tag(:query, "Title or Director") %>
  <%= text_field_tag(:query) %>

  <%= select_tag(:runtime, options_for_select([['Duration', 0], ['Under 90 minutes', 1], ['Between 90 & 120 minutes', 2], ['Over 120 minutes', 3]])) %>

  <%= submit_tag("Search") %>

  <%= button_tag(type: 'button') do %>
    <% link_to "Reset", movies_path %>
  <% end %>

<% end %>

<hr>

<% if @movies.empty? %>
  <h3>No movies found</h3>
<% else%>
  <% @movies.each do |movie| %>
    <%= render partial: "movie", locals: { movie: movie } %>
  <% end %>
<% end %>

app/views/movies/search.html.erb
<h1>Rotten Mangoes</h1>
<h4><%= link_to "Back to all movies", movies_path %></h4>
<hr>


<hr>

<% if @movies.empty? %>
  <h3>No Movies found</h3>
<% else %>
  <% @movies.each do |movie| %>
    <%= link_to image_tag(movie.image.thumb.url), movie_path(movie) %>
    <h2><%= link_to movie.title, movie_path(movie) %></h2>
    <h3><%= formatted_date(movie.release_date) %></h3>
    <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
    <p>Average rating from users: <%= movie.review_average %>/10</p>
    <p><%= movie.description %></p>
    <hr>
  <% end %>
<% end %>

app/views/movies/show.html.erb
<h4><%= link_to "Back to all movies", movies_path %></h4>

<br>

<%= link_to image_tag(@movie.image), movie_path(@movie) %>
<h2> <%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %> | <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %></p>
    <small>Posted by: <%= link_to review.user.full_name, user_path(review.user_id) %></small><br>
  <% end %>

  <br>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_sessions_path %> to see review and add your own.</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<h4><%= link_to "Back to all movies", movies_path %></h4>

<br>
  <h3><%= @user.full_name %>'s reviews </h3>
<br>

<% @user.reviews.each do |review| %>
  <p>Review for: <%= review.movie.title %></p>
  <p><%= review.text %></p>
  <p><%= review.rating_out_of_ten %></p>
  <br>
<% end %>